language: python
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
matrix:
  fast_finish: true
before_install:
  - pip3 install -U pip
  - pip3 install -U pytest
  - pip3 install codecov
  - pip3 install --upgrade pip setuptools wheel
  - pip3 install --only-binary=all numpy scipy pandas scikit-learn nltk
install:
  - pip3 install ".[test,sklearn,nltk]"
script:
  - python3 -m pytest
after_success:
  - python3 -m codecov
