language: python
python:
- '3.5'
- '3.6'
# notifications:
#   email:
#     on_success: change
#     on_failure: always
before_install:
  - pip install codecov
  # required for the pip only-binary fkag
  - pip install --upgrade pip setuptools wheel
  # we don't want to compile sources for the following packages:
  - pip install nltk
  - pip install --only-binary=numpy numpy
  - pip install --only-binary=scipy scipy
  - pip install --only-binary=pandas pandas
  - pip install --only-binary=scikit-learn scikit-learn
install:
  - pip install ".[test,sklearn,nltk]"
script: pytest --cov=pdpipe
after_success:
  - codecov
