language: python
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
  # coverage submission packages
  - pip install codecov
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy numpy
  - pip install --only-binary=scipy scipy
  - pip install --only-binary=scikit-learn scikit-learn
  # # setup miniconda
  # - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  # - chmod +x miniconda.sh
  # - ./miniconda.sh -b
  # - export PATH=/home/travis/miniconda3/bin:$PATH
  # - conda update --yes conda
  # # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  # - sudo rm -rf /dev/shm
  # - sudo ln -s /run/shm /dev/shm
install:
  # Coveralls 4.0 doesn't support Python 3.2
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
  - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi
  # - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy scikit-learn
  - python setup.py test
script: pytest --doctest-modules --cov=pdpipe
# --ignore-files="tests_perf\.py" -coveralls
# submit coverage
after_success:
  # - coveralls
  - codecov
deploy:
  provider: pypi
  user: shaypal5
  password:
    secure: RaTkue2YoXAkT/byvecFuOYdrJpHchCSMYnV4xqUFhQgT8qbyv7/EL+pm6sQ75Ni/JKAhSBdW8l4faKY9X1vW3yc5E2YHBf/81VJo1+JAbD9vGX0RLZbDzIsEVht+hL2Xxvab5Xh3fI7Pcr+cozKKMZxcOvEEwGo5DENM4CquGLeYyUxQOyhwSVjA+54bucFm+u+BA0QxUSHSyFy0cPKJVi8jNMSK/XAvs+Zk26o/MOU3udSj25FBtTkqPTBphaUNkt2EPGK1ZWkS9uhqs+hrETMWj6n6k49WblXvMDJiUtCIM+36Q+GBH/9UxCWuMOjL+uRFjVwwKQEcend9YMvp4+jRZ1HsLAWjMMhazxgkZ6M7bErHRxyabb7om+5IMptPdIo31gw8S1dKktGyuiSVYqs9X2mGA//SoItoDjIAUI81TQ3s2QLw5SfyEARfAdN+QS2aRaZHc0RPcLb10xNu7d7cy/4I88W+dptNqVABCP26Jlg4xsrRGMnONMSt/kWg1enXfgSXJcyrqqAaZzQUs/5QmVGtU4DBl3C8pUiHs6eGdpcqO3vpYoHveNT0WzoONkqZBvzBOjUWf8oMJzI3LcmCruUtktyd9cnlzM49pndnCyXPIKcpqPSGtR0FS3I/QhP7RBB+5xjP39SIuFsEW6ciakOs+AdMePl8tAq01o=
  distributions: sdist bdist_wheel
  on:
    all_branches: true
    tags: true
    repo: shaypal5/pdpipe
    condition: $TRAVIS_PYTHON_VERSION = "3.5"
  skip_upload_docs: true
