language: python
# ===== Linux =====
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - "3.6-dev"
  - "3.7-dev"
  - "3.8-dev"
matrix:
  fast_finish: true
  allow_failures:
    - python: 3.8
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "3.8-dev"
  include: 
    # ======= OSX ========
    - name: "Python 3.6.5 on macOS 10.13"
      os: osx
      osx_image: xcode9.4  # Python 3.6.5 running on macOS 10.13
      language: shell       # 'language: python' is an error on Travis CI macOS
before_install:
  - pip3 install -U pip
  - pip3 install -U pytest
  - pip3 install codecov
  - pip3 install --upgrade pip setuptools wheel
  - pip3 install --only-binary=all numpy scipy pandas scikit-learn nltk
install:
  - pip3 install ".[test,sklearn,nltk]"
script:
  - python3 -m pytest
after_success:
  - python3 -m codecov
